name: SSH Debug Demo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up tmate for SSH debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          # Optional: Limit session duration (in minutes)
          timeout-minutes: 15
          
      # Example step to demonstrate debugging
      - name: Create sample file
        run: |
          echo "This is a test file" > debug_test.txt
          ls -la
          
      # Example step with intentional error for debugging
      - name: Demonstrate error
        run: |
          echo "Trying to access non-existent file"
          cat nonexistent_file.txt || echo "Error occurred - use SSH to debug!"
